import type { Locale } from "../../i18n";

const zh = {
  title: "插件调试场",
  subtitle: "连续测试已接入的业务能力，并在同一页面查看回复、工具调用和平台检查结果。",
  history: "会话记录",
  search: "按会话、运行记录或追踪编号筛选",
  noRuns: "还没有运行记录。发送第一条请求后会出现在这里。",
  noMatches: "没有匹配的运行。清除筛选或发送新请求。",
  resultsCount: (count: number) => `${count} 条运行`,
  clearFilters: "清除筛选",
  loading: "加载中…",
  loadingRun: "正在加载运行证据…",
  saved: "已保存",
  runComplete: "运行已完成，证据已持久化",
  saving: "保存中…",
  exporting: "导出中…",
  exportDone: "已导出",
  queryHint: "按 Ctrl/Cmd + Enter 发送",
  routeHint: "选择要测试的业务能力；平台只会把当前有权限的工具交给模型。",
  routeName: (route: string, description?: string) => ({
    echo: "基础对话回显",
    demo_tools: "工具调用演示",
    demo_readonly: "只读订单查询",
    demo_llm: "模型问答演示",
    demo_rag: "知识检索问答",
    demo_approval_write: "需审批的写入操作",
    demo_multi_agent: "多角色协作",
    work_order_ops: "工单运营",
  }[route] ?? description ?? route),
  runtime: "运行模式",
  persistence: "数据持久化",
  postgres: "PostgreSQL",
  fake: "Fake 演示",
  real: "真实模型",
  ready: "就绪",
  pending: "等待操作",
  newThread: "新会话",
  request: "请求",
  route: "要测试的业务能力",
  model: "使用的模型",
  thread: "会话标识",
  query: "消息",
  extra: "附加 JSON",
  advanced: "高级请求字段",
  send: "发送",
  cancel: "取消",
  replay: "载入请求",
  copyCurl: "复制 curl",
  copied: "已复制",
  invalidJson: "附加字段必须是 JSON 对象。",
  answer: "业务输出",
  emptyAnswer: "选择一条历史运行或发送请求后，此处显示对话结果。",
  extensions: "结构化扩展",
  inspector: "运行详情",
  overview: "概览",
  timing: "处理过程",
  tools: "工具",
  contract: "平台检查",
  raw: "原始记录",
  notes: "标注",
  noSelection: "选择一条运行记录以查看平台证据。",
  run: "运行编号",
  trace: "追踪编号",
  status: "状态",
  duration: "耗时",
  events: "过程记录",
  export: "导出 JSONL",
  passed: "通过",
  failed: "失败",
  noTools: "本次运行没有工具调用。",
  noAnnotations: "还没有标注。用标注记录可复现的问题或验收观察。",
  noEvents: "没有事件。",
  gap: "至下一事件",
  addNote: "保存标注",
  category: "类型",
  note: "备注",
  badcase: "问题样本",
  reason: "问题或观察",
  expected: "期望行为",
  tags: "标签（逗号分隔）",
  delete: "删除",
  diagnostics: "整体检查",
  totalRuns: "运行",
  contractFailures: "平台检查失败",
  badcases: "问题样本",
  annotations: "标注",
  live: "实时",
  refresh: "刷新",
  filterAll: "全部状态",
  statusDone: "已完成",
  statusAwaitingApproval: "等待审批",
  statusError: "失败",
  statusCancelled: "已取消",
  doubleFire: "验证重复发送",
  threadBusy: "同一会话仍在处理中，平台已阻止重复发送。",
  requestFailed: "请求失败",
  arguments: "输入参数",
  toolResult: "工具返回",
  unknownTool: "未命名工具",
  checkName: (key: string) => ({
    terminal_event: "是否正常结束",
    run_id: "运行编号是否一致",
    trace_id: "追踪编号是否一致",
    sequence: "记录顺序是否连续",
    duplicate_event_ids: "是否有重复记录",
  }[key] ?? key),
  workOrderResult: "参考业务渲染",
};

const en: typeof zh = {
  title: "Plugin Playground",
  subtitle: "Exercise connected business capabilities and inspect the reply, tool calls, and platform checks in one place.",
  history: "Conversation history",
  search: "Filter by conversation, run, or trace ID",
  noRuns: "No runs yet. Send the first request to create one.",
  noMatches: "No runs match this filter. Clear the filter or send a new request.",
  resultsCount: (count: number) => `${count} runs`,
  clearFilters: "Clear filters",
  loading: "Loading…",
  loadingRun: "Loading run evidence…",
  saved: "Saved",
  runComplete: "Run complete; evidence persisted",
  saving: "Saving…",
  exporting: "Exporting…",
  exportDone: "Exported",
  queryHint: "Press Ctrl/Cmd + Enter to send",
  routeHint: "Choose a business capability to test; the platform only exposes tools you are allowed to use.",
  routeName: (route: string, description?: string) => ({
    echo: "Basic response echo",
    demo_tools: "Tool-call demonstration",
    demo_readonly: "Read-only order lookup",
    demo_llm: "Model Q&A demonstration",
    demo_rag: "Knowledge search Q&A",
    demo_approval_write: "Approval-gated write",
    demo_multi_agent: "Multi-agent collaboration",
    work_order_ops: "Work order operations",
  }[route] ?? description ?? route),
  runtime: "Runtime",
  persistence: "Persistence",
  postgres: "PostgreSQL",
  fake: "Fake demo",
  real: "Real model",
  ready: "Ready",
  pending: "Ready for input",
  newThread: "New thread",
  request: "Request",
  route: "Business capability",
  model: "Model to use",
  thread: "Conversation ID",
  query: "Message",
  extra: "Extra JSON",
  advanced: "Advanced request fields",
  send: "Send",
  cancel: "Cancel",
  replay: "Load request",
  copyCurl: "Copy curl",
  copied: "Copied",
  invalidJson: "Extra fields must be a JSON object.",
  answer: "Business output",
  emptyAnswer: "Select a historical run or send a request to inspect its result.",
  extensions: "Structured extensions",
  inspector: "Run details",
  overview: "Overview",
  timing: "Processing",
  tools: "Tools",
  contract: "Platform checks",
  raw: "Raw records",
  notes: "Annotations",
  noSelection: "Select a run to inspect its platform evidence.",
  run: "Run ID",
  trace: "Trace ID",
  status: "Status",
  duration: "Duration",
  events: "Records",
  export: "Export JSONL",
  passed: "Passed",
  failed: "Failed",
  noTools: "This run did not invoke a tool.",
  noAnnotations: "No annotations yet. Record reproducible issues or acceptance observations here.",
  noEvents: "No events.",
  gap: "To next event",
  addNote: "Save annotation",
  category: "Type",
  note: "Note",
  badcase: "Problem sample",
  reason: "Issue or observation",
  expected: "Expected behavior",
  tags: "Tags (comma separated)",
  delete: "Delete",
  diagnostics: "Overall checks",
  totalRuns: "Runs",
  contractFailures: "Platform check failures",
  badcases: "Problem samples",
  annotations: "Annotations",
  live: "Live",
  refresh: "Refresh",
  filterAll: "All statuses",
  statusDone: "Done",
  statusAwaitingApproval: "Awaiting approval",
  statusError: "Error",
  statusCancelled: "Cancelled",
  doubleFire: "Check duplicate-send protection",
  threadBusy: "This conversation is still processing; the platform blocked the duplicate request.",
  requestFailed: "Request failed",
  arguments: "Input arguments",
  toolResult: "Tool response",
  unknownTool: "Unnamed tool",
  checkName: (key: string) => ({
    terminal_event: "Ended normally",
    run_id: "Consistent run ID",
    trace_id: "Consistent trace ID",
    sequence: "Continuous record order",
    duplicate_event_ids: "No duplicate records",
  }[key] ?? key),
  workOrderResult: "Reference business renderer",
};

export type PlaygroundCopy = typeof zh;
export function playgroundCopy(locale: Locale): PlaygroundCopy {
  return locale === "en" ? en : zh;
}
