import type { Locale } from "../../i18n";

const zh = {
  title: "插件调试场",
  subtitle: "连续测试任意 domain，并把一次运行的业务结果、工具轨迹与平台契约放在同一视图。",
  history: "会话与运行",
  search: "筛选 thread、run 或 trace",
  noRuns: "还没有运行记录。发送第一条请求后会出现在这里。",
  newThread: "新会话",
  request: "请求",
  route: "Domain 路由",
  model: "模型别名",
  thread: "Thread ID",
  query: "消息",
  extra: "附加 JSON",
  advanced: "高级请求字段",
  send: "发送",
  cancel: "取消",
  replay: "载入请求",
  copyCurl: "复制 curl",
  copied: "已复制",
  invalidJson: "附加字段必须是 JSON 对象。",
  answer: "业务输出",
  emptyAnswer: "选择一条历史运行或发送请求后，此处显示对话结果。",
  extensions: "结构化扩展",
  inspector: "运行检查器",
  overview: "概览",
  timing: "时序",
  tools: "工具",
  contract: "契约",
  raw: "原始事件",
  notes: "标注",
  noSelection: "选择一个 run 以查看平台证据。",
  run: "Run",
  trace: "Trace",
  status: "状态",
  duration: "耗时",
  events: "事件",
  export: "导出 JSONL",
  passed: "通过",
  failed: "失败",
  noTools: "本次运行没有工具调用。",
  noEvents: "没有事件。",
  gap: "至下一事件",
  addNote: "保存标注",
  category: "类型",
  note: "备注",
  badcase: "Badcase",
  reason: "问题或观察",
  expected: "期望行为",
  tags: "标签（逗号分隔）",
  delete: "删除",
  diagnostics: "聚合诊断",
  totalRuns: "运行",
  contractFailures: "契约失败",
  badcases: "Badcase",
  annotations: "标注",
  live: "实时",
  refresh: "刷新",
  filterAll: "全部状态",
  doubleFire: "测试 409",
  threadBusy: "同一 thread 正在运行，平台已拒绝并发请求。",
  requestFailed: "请求失败",
  workOrderResult: "参考业务渲染",
};

const en: typeof zh = {
  title: "Plugin Playground",
  subtitle: "Exercise any domain continuously, with business output, tool traces, and platform contracts in one view.",
  history: "Threads and runs",
  search: "Filter thread, run, or trace",
  noRuns: "No runs yet. Send the first request to create one.",
  newThread: "New thread",
  request: "Request",
  route: "Domain route",
  model: "Model alias",
  thread: "Thread ID",
  query: "Message",
  extra: "Extra JSON",
  advanced: "Advanced request fields",
  send: "Send",
  cancel: "Cancel",
  replay: "Load request",
  copyCurl: "Copy curl",
  copied: "Copied",
  invalidJson: "Extra fields must be a JSON object.",
  answer: "Business output",
  emptyAnswer: "Select a historical run or send a request to inspect its result.",
  extensions: "Structured extensions",
  inspector: "Run inspector",
  overview: "Overview",
  timing: "Timing",
  tools: "Tools",
  contract: "Contract",
  raw: "Raw events",
  notes: "Annotations",
  noSelection: "Select a run to inspect platform evidence.",
  run: "Run",
  trace: "Trace",
  status: "Status",
  duration: "Duration",
  events: "Events",
  export: "Export JSONL",
  passed: "Passed",
  failed: "Failed",
  noTools: "This run did not invoke a tool.",
  noEvents: "No events.",
  gap: "To next event",
  addNote: "Save annotation",
  category: "Type",
  note: "Note",
  badcase: "Badcase",
  reason: "Issue or observation",
  expected: "Expected behavior",
  tags: "Tags (comma separated)",
  delete: "Delete",
  diagnostics: "Aggregate diagnostics",
  totalRuns: "Runs",
  contractFailures: "Contract failures",
  badcases: "Badcases",
  annotations: "Annotations",
  live: "Live",
  refresh: "Refresh",
  filterAll: "All statuses",
  doubleFire: "Test 409",
  threadBusy: "The platform rejected a concurrent request on this thread.",
  requestFailed: "Request failed",
  workOrderResult: "Reference business renderer",
};

export type PlaygroundCopy = typeof zh;
export function playgroundCopy(locale: Locale): PlaygroundCopy {
  return locale === "en" ? en : zh;
}
